pipeline {
    agent any

    environment {
            AWS_REGION = 'us-east-1'             
            AWS_ACCOUNT_ID = '025889067332'
            REPO_GH = 'https://github.com/GuidoAnd/DevOps-Integration-Proyect.git'           
            BRANCH_TARGET_NAME = 'main'
            ECR_URL = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/devops-pi/reginf"
            FULL_IMAGE = "${ECR_URL}:${IMAGE_TAG}"
            HELM_REPO = 'https://github.com/GuidoAnd/DevOps-Integration-Proyect-helm.git'
            GH_PUSH_URL_HELM = 'github.com/GuidoAnd/DevOps-Integration-Proyect-helm.git'
            BRANCH_HELM = 'main'
    }   

    stages {        
        stage('Clean WS') {
            steps {
                deleteDir()
            }
        }

        stage('Checkout') {
            steps {
                git branch: "${BRANCH_TARGET_NAME}",
                    url: "${REPO_GH}"
                script {
                    env.GIT_COMMIT_SHORT = sh(script: 'git rev-parse HEAD', 
                    returnStdout: true).trim()
                    env.IMAGE_TAG = env.GIT_COMMIT_SHORT
                }
            }
        }

        stage('Build Image for Test') {
            steps {
                sh "docker build . -t ${FULL_IMAGE}-test"                
            }
        }

        stage('Tests'){
            steps {
                sh "docker run --rm ${FULL_IMAGE}-test pytest tests"
            }
        }

        stage('Build Image') {
            steps {
                sh "docker build . -t ${FULL_IMAGE}"
              }
            }
                       

        stage('Login to ECR && Push'){
            steps {
                // script {
                 //   withCredentials([usernamePassword(credentialsId: 'Jenkins-ECR-pi', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                        sh """
                        aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                        docker tag ${FULL_IMAGE} ${ECR_URL}:${IMAGE_TAG}
                        docker tag ${FULL_IMAGE} ${ECR_URL}:latest
                        docker push ${ECR_URL}:${IMAGE_TAG}
                        docker push ${ECR_URL}:latest
                        """
               }         
          //  }
        }
        stage('Update Helm Values') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-j-app',
                                 passwordVariable: 'GIT_PASSWORD',
                                 usernameVariable: 'GIT_USERNAME')]) {
                    script {

                        sh """
                            rm -rf helm-repo
                            git clone ${HELM_REPO} helm-repo                            
                        """
                                           
                        dir('helm-repo') {
                            sh "yq -i '".tag = \"${IMAGE_TAG}\"' helm/poke-manifests/values.yaml"

                            sh """                                
                                git config user.email "jenkins@ordersgh17.com"
                                git config user.name "Jenkins CI"
                                git add helm/poke-manifests/values.yaml                                
                                git diff --quiet || (git commit -m "Update image tag to ${IMAGE_TAG}" && git push https://${GIT_USERNAME}:${GIT_PASSWORD}@${GH_PUSH_URL_HELM} ${BRANCH_HELM})                                                                 
                            """   
                                }   
                            }
                        }

                 }
            }
        
    }
}               